/* AUTOGENERATED FILE. DO NOT EDIT. RUN "yarn generate:asset-index" TO REGENERATE. */
import type {ImageRequireSource} from 'react-native';
import type {AssetManifest} from '@/shared/lib';
export default {} satisfies AssetManifest;
