/* AUTOGENERATED FILE. DO NOT EDIT. RUN "yarn generate:asset-index" TO REGENERATE. */
import type {ImageRequireSource} from 'react-native';
import type {AssetManifest} from '@/shared/lib';
export default {
  arrowLeft: {
    source: require('./arrowLeft.png') as ImageRequireSource,
    width: 24,
    height: 24,
    color: 'neutralFgPrimary',
  },
  arrowRight: {
    source: require('./arrowRight.png') as ImageRequireSource,
    width: 24,
    height: 24,
    color: 'neutralFgPrimary',
  },
  close: {
    source: require('./close.png') as ImageRequireSource,
    width: 24,
    height: 24,
    color: 'neutralFgPrimary',
  },
} satisfies AssetManifest;
