# You Podfile should look similar to this file. React Native currently does not support use_frameworks!

# This requires CocoaPods 1.7.2+
source 'https://cdn.cocoapods.org/'
# add more sources using environment key ios.pods.sources
# ADDITIONAL_POD_SOURCES

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
platform :ios, '10.0'

# ignore all warnings from all pods
inhibit_all_warnings!

target 'FLAGSHIP' do
  config = use_native_modules!

  use_react_native!

  # Add new pods below this line


  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
      # If pod's target ios build version is lower than 9.0 update them to build against minimum of 9.
        if Gem::Version.new('9.0') > Gem::Version.new(config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'])
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        end
      end
    end
  end

end
