export const plugins = [
  'plugin-app-icon',
  'plugin-asset',
  'plugin-fastlane',
  'plugin-fbsdk-next',
  'plugin-firebase-analytics',
  'plugin-firebase-app',
  'plugin-google-signin',
  'plugin-leanplum',
  'plugin-native-navigation',
  'plugin-permissions',
  'plugin-splash-screen',
  'plugin-target-application',
  'plugin-target-extension',
];
