version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    commit_message:
      prefix: "chore"
      include_scope: false
    ignored_updates:
      - match:
          dependency_name: "react-native"
      - match:
          dependency_name: "metro-react-native-babel-preset"
      - match:
          dependency_name: "@babel/core"
      - match:
          dependency_name: "@babel/runtime"
      - match:
          dependency_name: "@types/react"
      - match:
          dependency_name: "@types/react-native"
      - match:
          dependency_name: "react-native-navigation"
      - match:
          dependency_name: "react"
      - match:
          dependency_name: "react-dom"
      - match:
          dependency_name: "@react-native-community/cli-platform-ios"
      - match:
          dependency_name: "@react-native-community/cli-platform-android"
