export const ios = {
  AppTrackingTransparency: {
    pod: "AppTrackingTransparency",
    usageKey: "NSUserTrackingUsageDescription",
    purposeKey: undefined,
  },
  Bluetooth: {
    pod: "Blueooth",
    usageKey: "NSBluetoothAlwaysUsageDescription",
    purposeKey: undefined,
  },
  BluetoothPeripheral: {
    pod: "Bluetooth",
    usageKey: "NSBluetoothPeripheralUsageDescription",
    purposeKey: undefined,
  },
  Calendars: {
    pod: "Calendars",
    usageKey: "NSCalendarsUsageDescription",
    purposeKey: undefined,
  },
  Camera: {
    pod: "Camera",
    usageKey: "NSCameraUsageDescription",
    purposeKey: undefined,
  },
  Contacts: {
    pod: "Contacts",
    usageKey: "NSContactsUsageDescription",
    purposeKey: undefined,
  },
  FaceID: {
    pod: "FaceID",
    usageKey: "NSFaceIDUsageDescription",
    purposeKey: undefined,
  },
  LocationAccuracy: {
    pod: "LocationAccuracy",
    usageKey: "NSLocationTemporaryUsageDescriptionDictionary",
    purposeKey: "REQUIRED",
  },
  LocationAlways: {
    pod: "LocationAlways",
    usageKey: "NSLocationAlwaysAndWhenInUseUsageDescription",
    purposeKey: undefined,
  },
  LocationWhenInUse: {
    pod: "LocationWhenInUse",
    usageKey: "NSLocationWhenInUseUsageDescription",
    purposeKey: undefined,
  },
  MediaLibrary: {
    pod: "MediaLibrary",
    usageKey: undefined,
    purposeKey: undefined,
  },
  Microphone: {
    pod: "Microphone",
    usageKey: "NSMicrophoneUsageDescription",
    purposeKey: undefined,
  },
  Motion: {
    pod: "Motion",
    usageKey: "NSMotionUsageDescription",
    purposeKey: undefined,
  },
  Notifications: {
    pod: "Notifications",
    usageKey: undefined,
    purposeKey: undefined,
  },
  PhotoLibrary: {
    pod: "PhotoLibrary",
    usageKey: "NSPhotoLibraryUsageDescription",
    purposeKey: undefined,
  },
  PhotoLibraryAdd: {
    pod: "PhotoLibraryAddOnly",
    usageKey: "NSPhotoLibraryAddUsageDescription",
    purposeKey: undefined,
  },
  Reminders: {
    pod: "Reminders",
    usageKey: "NSRemindersFullAccessUsageDescription",
    purposeKey: undefined,
  },
  Siri: {
    pod: "Siri",
    usageKey: "NSSiriUsageDescription",
    purposeKey: undefined,
  },
  SpeechRecognition: {
    pod: "SpeechRecognition",
    usageKey: "NSSpeechRecognitionUsageDescription",
    purposeKey: undefined,
  },
};

export const android = [
  "ACCEPT_HANDOVER",
  "ACCESS_BACKGROUND_LOCATION",
  "ACCESS_COARSE_LOCATION",
  "ACCESS_FINE_LOCATION",
  "ACCESS_MEDIA_LOCATION",
  "ACTIVITY_RECOGNITION",
  "ADD_VOICEMAIL",
  "ANSWER_PHONE_CALLS",
  "BLUETOOTH_ADVERTISE",
  "BLUETOOTH_CONNECT",
  "BLUETOOTH_SCAN",
  "BODY_SENSORS",
  "BODY_SENSORS_BACKGROUND",
  "CALL_PHONE",
  "CAMERA",
  "GET_ACCOUNTS",
  "NEARBY_WIFI_DEVICES",
  "POST_NOTIFICATIONS",
  "PROCESS_OUTGOING_CALLS",
  "READ_CALENDAR",
  "READ_CALL_LOG",
  "READ_CONTACTS",
  "READ_EXTERNAL_STORAGE",
  "READ_MEDIA_AUDIO",
  "READ_MEDIA_IMAGES",
  "READ_MEDIA_VIDEO",
  "READ_PHONE_NUMBERS",
  "READ_PHONE_STATE",
  "READ_SMS",
  "RECEIVE_MMS",
  "RECEIVE_SMS",
  "RECEIVE_WAP_PUSH",
  "RECORD_AUDIO",
  "SEND_SMS",
  "USE_SIP",
  "UWB_RANGING",
  "WRITE_CALENDAR",
  "WRITE_CALL_LOG",
  "WRITE_CONTACTS",
  "WRITE_EXTERNAL_STORAGE",
] as const;
