/* AUTOGENERATED FILE. DO NOT EDIT. RUN "yarn generate:asset-index" TO REGENERATE. */
import type {ImageRequireSource} from 'react-native';
export default {
  account: require('./tabAccount.png') as ImageRequireSource,
  bag: require('./tabBag.png') as ImageRequireSource,
  foryou: require('./tabForyou.png') as ImageRequireSource,
  home: require('./tabHome.png') as ImageRequireSource,
  shop: require('./tabShop.png') as ImageRequireSource,
  wishlist: require('./tabWishlist.png') as ImageRequireSource,
} as const;
