#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if [ -t 1 ]; then
  exec </dev/tty
fi

./node_modules/.bin/commitlint -e $1
./tools/verify-commit.ts $1
./node_modules/.bin/nx workspace-lint
./node_modules/.bin/nx format:check --base HEAD
./node_modules/.bin/nx affected:test --base HEAD
./node_modules/.bin/nx affected:lint --base HEAD
