#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if [ -t 1 ]; then
  exec </dev/tty
fi

./node_modules/.bin/commitlint -e $1
./node_modules/.bin/nx workspace-lint

IS_AMEND=$(ps -wwo ppid=$PPID,command | grep 'git commit' | head -1 | grep -c -e '--amend' || [[ $? == 1 ]])
if [ -n "$IS_AMEND" ]; then
  ./node_modules/.bin/nx format:check --files $(git diff-tree --no-commit-id --name-only -r HEAD) $(git diff --name-only --cached)
  ./node_modules/.bin/nx affected:test --files $(git diff-tree --no-commit-id --name-only -r HEAD) $(git diff --name-only --cached)
  ./node_modules/.bin/nx affected:lint --files $(git diff-tree --no-commit-id --name-only -r HEAD) $(git diff --name-only --cached)
else
  ./tools/verify-commit.ts $1
  ./node_modules/.bin/nx format:check --files $(git diff --name-only --cached)
  ./node_modules/.bin/nx affected:test --files $(git diff --name-only --cached)
  ./node_modules/.bin/nx affected:lint --files $(git diff --name-only --cached)
fi
